// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBsupSwtbEOlTZu-Sw3PwJPN1U7tLQLl8',
    appId: '1:739217814520:web:9a896b78162e0c08ad1c0d',
    messagingSenderId: '739217814520',
    projectId: 'iot-fire-detecion',
    authDomain: 'iot-fire-detecion.firebaseapp.com',
    storageBucket: 'iot-fire-detecion.firebasestorage.app',
    measurementId: 'G-5022ND7R3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfLuWjARgeIlSEQ7ubxTg7FREef3Ca-TE',
    appId: '1:739217814520:android:c98a84716c7dc2c7ad1c0d',
    messagingSenderId: '739217814520',
    projectId: 'iot-fire-detecion',
    storageBucket: 'iot-fire-detecion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmvPBeBzWwWh_6Z4XAFg7mRaxlJ7vhfF8',
    appId: '1:739217814520:ios:624696923faa0bccad1c0d',
    messagingSenderId: '739217814520',
    projectId: 'iot-fire-detecion',
    storageBucket: 'iot-fire-detecion.firebasestorage.app',
    iosBundleId: 'com.example.iotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmvPBeBzWwWh_6Z4XAFg7mRaxlJ7vhfF8',
    appId: '1:739217814520:ios:624696923faa0bccad1c0d',
    messagingSenderId: '739217814520',
    projectId: 'iot-fire-detecion',
    storageBucket: 'iot-fire-detecion.firebasestorage.app',
    iosBundleId: 'com.example.iotApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBsupSwtbEOlTZu-Sw3PwJPN1U7tLQLl8',
    appId: '1:739217814520:web:ba75ca2dc57eff37ad1c0d',
    messagingSenderId: '739217814520',
    projectId: 'iot-fire-detecion',
    authDomain: 'iot-fire-detecion.firebaseapp.com',
    storageBucket: 'iot-fire-detecion.firebasestorage.app',
    measurementId: 'G-W6V5T5TT29',
  );
}
